on:
  push:
    branches:
      - "main"
      - "restructure"
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "README.md"

name: Test Build

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm install    
  
      - name: Generate build
        run: npm run build
        env:
          CI: false
      
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v7
        with:
          name: raspberry_extension_server_ui
          path: |
            build
            dist
