on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_run:
    workflows:
      - Manual Release
    types:
      - completed

name: Create Release

permissions:
  contents: write

jobs:

  build-project:
    name: Build Project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure all tags are fetched

      - name: Determine latest tag
        id: determine_latest_tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "latest_tag=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo "latest_tag=$latest_tag" >> $GITHUB_ENV
          fi
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Install dependencies
        run: npm install    

      - name: Generate build
        run: npm run build
        env:
          CI: false
      
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v4
        with:
          name: raspberry_extension_server_ui
          path: |
            build
            dist
    outputs:
      latest_tag: ${{ env.latest_tag }}

  release-project:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-project

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: raspberry_extension_server_ui
      - name: Test artifact download
        run: ls -R

      - name: Archive artifact
        uses: thedoctor0/zip-release@main
        with:
          filename: raspberry_extension_server_ui-release.zip

      - name: Create and Upload Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ needs.build-project.outputs.latest_tag }}
          name: Raspberry Extension Server UI release ${{ needs.build-project.outputs.latest_tag }}
          files: raspberry_extension_server_ui-release.zip
          make_latest: true
